---
kind: pipeline
type: kubernetes
name: 11-alpine

steps:
  - name: slim
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/11/alpine/slim/Dockerfile
      tags:
        - slim
      authjson_docker:
        from_secret: DOCKER_AUTH
  - name: jre
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/11/alpine/jre/Dockerfile
      tags:
        - jre
      authjson_docker:
        from_secret: DOCKER_AUTH
trigger:
  when:
    event: push
---
kind: pipeline
type: kubernetes
name: 11-debian

steps:
  - name: slim
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/11/debian/slim/Dockerfile
      tags:
        - slim
      authjson_docker:
        from_secret: DOCKER_AUTH
  - name: jre
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/11/debian/jre/Dockerfile
      tags:
        - jre
      authjson_docker:
        from_secret: DOCKER_AUTH
trigger:
  when:
    event: push
---
kind: pipeline
type: kubernetes
name: 11-openj9-alpine

steps:
  - name: slim
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/11-openj9/alpine/slim/Dockerfile
      tags:
        - slim
      authjson_docker:
        from_secret: DOCKER_AUTH
  - name: jre
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/11-openj9/alpine/jre/Dockerfile
      tags:
        - jre
      authjson_docker:
        from_secret: DOCKER_AUTH
trigger:
  when:
    event: push
---
kind: pipeline
type: kubernetes
name: 11-openj9-debian

steps:
  - name: slim
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/11-openj9/debian/slim/Dockerfile
      tags:
        - slim
      authjson_docker:
        from_secret: DOCKER_AUTH
  - name: jre
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/11-openj9/debian/jre/Dockerfile
      tags:
        - jre
      authjson_docker:
        from_secret: DOCKER_AUTH
trigger:
  when:
    event: push
---
kind: pipeline
type: kubernetes
name: 12-alpine

steps:
  - name: slim
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/12/alpine/slim/Dockerfile
      tags:
        - slim
      authjson_docker:
        from_secret: DOCKER_AUTH
  - name: jre
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/12/alpine/jre/Dockerfile
      tags:
        - jre
      authjson_docker:
        from_secret: DOCKER_AUTH
trigger:
  when:
    event: push
---
kind: pipeline
type: kubernetes
name: 12-debian

steps:
  - name: slim
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/12/debian/slim/Dockerfile
      tags:
        - slim
      authjson_docker:
        from_secret: DOCKER_AUTH
  - name: jre
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/12/debian/jre/Dockerfile
      tags:
        - jre
      authjson_docker:
        from_secret: DOCKER_AUTH
trigger:
  when:
    event: push
---
kind: pipeline
type: kubernetes
name: 12-openj9-alpine

steps:
  - name: slim
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/12-openj9/alpine/slim/Dockerfile
      tags:
        - slim
      authjson_docker:
        from_secret: DOCKER_AUTH
  - name: jre
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/12-openj9/alpine/jre/Dockerfile
      tags:
        - jre
      authjson_docker:
        from_secret: DOCKER_AUTH
trigger:
  when:
    event: push
---
kind: pipeline
type: kubernetes
name: 12-openj9-debian

steps:
  - name: slim
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/12-openj9/debian/slim/Dockerfile
      tags:
        - slim
      authjson_docker:
        from_secret: DOCKER_AUTH
  - name: jre
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/12-openj9/debian/jre/Dockerfile
      tags:
        - jre
      authjson_docker:
        from_secret: DOCKER_AUTH
trigger:
  when:
    event: push
---
kind: pipeline
type: kubernetes
name: 13-alpine

steps:
  - name: slim
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/13/alpine/slim/Dockerfile
      tags:
        - slim
      authjson_docker:
        from_secret: DOCKER_AUTH
  - name: jre
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/13/alpine/jre/Dockerfile
      tags:
        - jre
      authjson_docker:
        from_secret: DOCKER_AUTH
trigger:
  when:
    event: push
---
kind: pipeline
type: kubernetes
name: 13-debian

steps:
  - name: slim
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/13/debian/slim/Dockerfile
      tags:
        - slim
      authjson_docker:
        from_secret: DOCKER_AUTH
  - name: jre
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/13/debian/jre/Dockerfile
      tags:
        - jre
      authjson_docker:
        from_secret: DOCKER_AUTH
trigger:
  when:
    event: push
---
kind: pipeline
type: kubernetes
name: 13-openj9-alpine

steps:
  - name: slim
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/13-openj9/alpine/slim/Dockerfile
      tags:
        - slim
      authjson_docker:
        from_secret: DOCKER_AUTH
  - name: jre
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/13-openj9/alpine/jre/Dockerfile
      tags:
        - jre
      authjson_docker:
        from_secret: DOCKER_AUTH
trigger:
  when:
    event: push
---
kind: pipeline
type: kubernetes
name: 13-openj9-debian

steps:
  - name: slim
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/13-openj9/debian/slim/Dockerfile
      tags:
        - slim
      authjson_docker:
        from_secret: DOCKER_AUTH
  - name: jre
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/13-openj9/debian/jre/Dockerfile
      tags:
        - jre
      authjson_docker:
        from_secret: DOCKER_AUTH
trigger:
  when:
    event: push
---
kind: pipeline
type: kubernetes
name: 14-alpine

steps:
  - name: slim
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/14/alpine/slim/Dockerfile
      tags:
        - slim
      authjson_docker:
        from_secret: DOCKER_AUTH
  - name: jre
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/14/alpine/jre/Dockerfile
      tags:
        - jre
      authjson_docker:
        from_secret: DOCKER_AUTH
trigger:
  when:
    event: push
---
kind: pipeline
type: kubernetes
name: 14-debian

steps:
  - name: slim
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/14/debian/slim/Dockerfile
      tags:
        - slim
      authjson_docker:
        from_secret: DOCKER_AUTH
  - name: jre
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/14/debian/jre/Dockerfile
      tags:
        - jre
      authjson_docker:
        from_secret: DOCKER_AUTH
trigger:
  when:
    event: push
---
kind: pipeline
type: kubernetes
name: 14-openj9-alpine

steps:
  - name: slim
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/14-openj9/alpine/slim/Dockerfile
      tags:
        - slim
      authjson_docker:
        from_secret: DOCKER_AUTH
  - name: jre
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/14-openj9/alpine/jre/Dockerfile
      tags:
        - jre
      authjson_docker:
        from_secret: DOCKER_AUTH
trigger:
  when:
    event: push
---
kind: pipeline
type: kubernetes
name: 14-openj9-debian

steps:
  - name: slim
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/14-openj9/debian/slim/Dockerfile
      tags:
        - slim
      authjson_docker:
        from_secret: DOCKER_AUTH
  - name: jre
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: adoptopenjdk-spring-base
      cache: false
      dockerfile: /drone/src/14-openj9/debian/jre/Dockerfile
      tags:
        - jre
      authjson_docker:
        from_secret: DOCKER_AUTH
trigger:
  when:
    event: push
