---
kind: pipeline
name: 11-alpine

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 11/alpine/Dockerfile
      tags:
        - 11-alpine
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 11-alpine-slim

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 11/alpine/slim/Dockerfile
      tags:
        - 11-alpine-slim
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 11-alpine-jre

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 11/alpine/jre/Dockerfile
      tags:
        - 11-alpine-jre
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 11-debian

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 11/debian/Dockerfile
      tags:
        - 11-debian
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 11-debian-slim

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 11/debian/slim/Dockerfile
      tags:
        - 11-debian-slim
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 11-debian-jre

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 11/debian/jre/Dockerfile
      tags:
        - 11-debian-jre
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 11-openj9-alpine

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 11-openj9/alpine/Dockerfile
      tags:
        - 11-openj9-alpine
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 11-openj9-alpine-slim

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 11-openj9/alpine/slim/Dockerfile
      tags:
        - 11-openj9-alpine-slim
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 11-openj9-alpine-jre

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 11-openj9/alpine/jre/Dockerfile
      tags:
        - 11-openj9-alpine-jre
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 11-openj9-debian

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 11-openj9/debian/Dockerfile
      tags:
        - 11-openj9-debian
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 11-openj9-debian-slim

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 11-openj9/debian/slim/Dockerfile
      tags:
        - 11-openj9-debian-slim
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 11-openj9-debian-jre

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 11-openj9/debian/jre/Dockerfile
      tags:
        - 11-openj9-debian-jre
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 12-alpine

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 12/alpine/Dockerfile
      tags:
        - 12-alpine
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 12-alpine-slim

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 12/alpine/slim/Dockerfile
      tags:
        - 12-alpine-slim
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 12-alpine-jre

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 12/alpine/jre/Dockerfile
      tags:
        - 12-alpine-jre
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 12-debian

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 12/debian/Dockerfile
      tags:
        - 12-debian
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 12-debian-slim

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 12/debian/slim/Dockerfile
      tags:
        - 12-debian-slim
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 12-debian-jre

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 12/debian/jre/Dockerfile
      tags:
        - 12-debian-jre
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 12-openj9-alpine

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 12-openj9/alpine/Dockerfile
      tags:
        - 12-openj9-alpine
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 12-openj9-alpine-slim

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 12-openj9/alpine/slim/Dockerfile
      tags:
        - 12-openj9-alpine-slim
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 12-openj9-alpine-jre

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 12-openj9/alpine/jre/Dockerfile
      tags:
        - 12-openj9-alpine-jre
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 12-openj9-debian

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 12-openj9/debian/Dockerfile
      tags:
        - 12-openj9-debian
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 12-openj9-debian-slim

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 12-openj9/debian/slim/Dockerfile
      tags:
        - 12-openj9-debian-slim
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 12-openj9-debian-jre

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 12-openj9/debian/jre/Dockerfile
      tags:
        - 12-openj9-debian-jre
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 13-alpine

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 13/alpine/Dockerfile
      tags:
        - 13-alpine
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 13-alpine-slim

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 13/alpine/slim/Dockerfile
      tags:
        - 13-alpine-slim
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 13-alpine-jre

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 13/alpine/jre/Dockerfile
      tags:
        - 13-alpine-jre
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 13-debian

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 13/debian/Dockerfile
      tags:
        - 13-debian
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 13-debian-slim

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 13/debian/slim/Dockerfile
      tags:
        - 13-debian-slim
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 13-debian-jre

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 13/debian/jre/Dockerfile
      tags:
        - 13-debian-jre
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 13-openj9-alpine

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 13-openj9/alpine/Dockerfile
      tags:
        - 13-openj9-alpine
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 13-openj9-alpine-slim

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 13-openj9/alpine/slim/Dockerfile
      tags:
        - 13-openj9-alpine-slim
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 13-openj9-alpine-jre

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 13-openj9/alpine/jre/Dockerfile
      tags:
        - 13-openj9-alpine-jre
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 13-openj9-debian

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 13-openj9/debian/Dockerfile
      tags:
        - 13-openj9-debian
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 13-openj9-debian-slim

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 13-openj9/debian/slim/Dockerfile
      tags:
        - 13-openj9-debian-slim
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
---
kind: pipeline
name: 13-openj9-debian-jre

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/adoptopenjdk-spring-base
      dockerfile: 13-openj9/debian/jre/Dockerfile
      tags:
        - 13-openj9-debian-jre
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push
